branch-defaults:
  default:
    environment: null
global:
  application_name: assign4
  default_ec2_keyname: aws-tools
  default_platform: 64bit Amazon Linux 2015.03 v1.4.3 running Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: null
